[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
console_log = "0.2"
wasm-logger = "0.2"
log = "0.4"
web-sys = { version = "0.3", features = ["Window"] }
